### ISSUE TITLE
No data present on portfolio

### ISSUE THREAD

**Issue by itsDigvijaysing** [amolnidankar/portfolio#1]
Please add data in Portfoliosite 😊

**Comment by itsDigvijaysing** [comment]
Index html found 😅🎉
Good work 👏

**Comment by amolnidankar** [comment]
Hi ,
It's not completed. Once completed I will update Readme with Domina name.🙂🙂

**Comment by amolnidankar** [comment]
Hi ,
It's not completed. After completion I will update Readme with Domain name.🙂🙂
